/**
 * React Query 键：第一段是资源名，其后是定位参数。
 * 失效时按前缀匹配（`queryClient.invalidateQueries({ queryKey: queryKeys.releases(serviceId) })`）。
 */
export const queryKeys = {
  me: () => ['me'] as const,
  users: () => ['users'] as const,
  projects: () => ['projects'] as const,
  project: (projectId: string) => ['projects', projectId] as const,
  members: (projectId: string) => ['projects', projectId, 'members'] as const,
  quota: (projectId: string) => ['projects', projectId, 'quota'] as const,
  services: () => ['services'] as const,
  service: (serviceId: string) => ['services', serviceId] as const,
  slots: (serviceId: string) => ['services', serviceId, 'slots'] as const,
  releases: (serviceId: string) => ['services', serviceId, 'releases'] as const,
  release: (releaseId: string) => ['releases', releaseId] as const,
  trafficSwitches: (serviceId: string) => ['services', serviceId, 'traffic-switches'] as const,
  branches: (projectId: string) => ['projects', projectId, 'branches'] as const,
  devSession: (projectId: string) => ['projects', projectId, 'dev-session'] as const,
  task: (taskId: string) => ['tasks', taskId] as const,
  agents: (taskId: string) => ['tasks', taskId, 'agents'] as const,
  dataBindings: (projectId: string) => ['projects', projectId, 'data-bindings'] as const,
  config: (projectId: string, env: string) => ['projects', projectId, 'config', env] as const,
  operations: (serviceId?: string) => (serviceId === undefined ? (['operations'] as const) : (['operations', serviceId] as const)),
  operationSpec: (operationKey: string) => ['operations', 'spec', operationKey] as const,
  accessRequests: (serviceId?: string) => (serviceId === undefined ? (['access-requests'] as const) : (['access-requests', serviceId] as const)),
  subscriptions: (projectId: string) => ['projects', projectId, 'subscriptions'] as const,
  deliveries: (projectId: string) => ['projects', projectId, 'deliveries'] as const,
  logs: (projectId: string) => ['projects', projectId, 'logs'] as const,
  health: (serviceId: string) => ['services', serviceId, 'health'] as const,
  alerts: (projectId: string) => ['projects', projectId, 'alerts'] as const,
  trace: (traceId: string) => ['traces', traceId] as const,
  capabilities: (projectId: string) => ['projects', projectId, 'capabilities'] as const,
  egressEntries: (projectId?: string) => (projectId === undefined ? (['egress', 'entries'] as const) : (['egress', 'entries', projectId] as const)),
  egressRequests: (projectId?: string) => (projectId === undefined ? (['egress', 'requests'] as const) : (['egress', 'requests', projectId] as const)),
  egressBlocked: (projectId: string) => ['egress', 'blocked', projectId] as const,
  servicePlans: () => ['service-plans'] as const,
  taskProfiles: () => ['task-profiles'] as const,
} as const;
