import { describe, expect, test } from 'bun:test';
import { sql } from 'drizzle-orm';
import { ResourceIdSchema, WorkspaceLayoutSchema } from '@crewstation/contracts';
import { createFakeK8sClient } from '@crewstation/k8s';
import { noopLogger } from '@crewstation/kernel';
import { runMigrations } from '@crewstation/persistence';
import { loadPlatformSettings } from '@crewstation/settings';
import { createTestDatabase, testDatabaseAvailable } from '@crewstation/testkit';
import { createPlatformModule } from '../wiring';

const available = await testDatabaseAvailable();
describe.skipIf(!available)('RFC-013 atomic resource upgrade', () => {
  test('all owners upgrade an existing database together, preserving physical names and immutable manifests', async () => {
    const tdb = await createTestDatabase();
    try {
      const settings = loadPlatformSettings({ CS_DATABASE_URL: tdb.url, CS_SECRET_KEY: Buffer.alloc(32, 1).toString('base64'), CS_GITLAB_URL: 'http://127.0.0.1:9' });
      const platform = createPlatformModule({ db: tdb.db, settings, k8s: createFakeK8sClient(), logger: noopLogger, instance: 'identity-upgrade' });
      const migrations = platform.api.migrations;
      await runMigrations(tdb.db, migrations.map((set) => ({ ...set, files: set.files.filter((file) => !file.name.includes('resource_identity')) })));
      const user = 'usr_00000000000000000000000000000042', project = 'prj_00000000000000000000000000000042', service = 'svc_00000000000000000000000000000042', task = 'tsk_00000000000000000000000000000042', release = 'rel_00000000000000000000000000000042';
      await tdb.db.execute(sql`INSERT INTO identity.users (id, external_id, name, email, created_at, last_login_at) VALUES (${user}, 'old:42', 'Owner', 'owner@example.com', now(), now())`);
      await tdb.db.execute(sql`INSERT INTO project.projects (id, slug, name, kind, namespace, owner_user_id, state, template, created_by, created_at, updated_at) VALUES (${project}, 'sample', 'Sample', 'DigitalWorker', 'cs-sample', ${user}, 'active', 'minimal-sample', ${user}, now(), now())`);
      await tdb.db.execute(sql`INSERT INTO project.services (id, project_id, name, kind, identity, created_at) VALUES (${service}, ${project}, 'sample', 'DigitalWorker', 'sample/sample', now())`);
      const manifest = { apiVersion: 'crewstation/v1', kind: 'DigitalWorker', spec: { service: { command: ['app'], port: 3000, plan: 'standard-small' }, env: [{ name: 'GREETING', from: 'config', default: 'hello' }], tasks: { profile: 'coding-medium', agentProfiles: [{ name: 'chat', compute: 'default' }], outputContracts: [] }, apis: { requested: [] }, subscriptions: [] } };
      await tdb.db.execute(sql`INSERT INTO release.releases (id, service_id, project_id, tag, commit_sha, branch, status, target_slot, manifest, pipeline, created_by, created_at, updated_at) VALUES (${release}, ${service}, ${project}, 'v1.0.0', ${'a'.repeat(40)}, 'main', 'ready', 'blue', ${JSON.stringify(manifest)}::text::jsonb, '{}', ${user}, now(), now())`);
      await tdb.db.execute(sql`INSERT INTO task_runtime.environments (id, project_id, service_id, kind, state, volume_mode, profile, namespace, pod_name, pvc_name, trace_id, runner_token_hash, labels, created_by, created_at, updated_at, last_activity_at) VALUES (${task}, ${project}, ${service}, 'dev-session', 'running', 'persistent', 'coding-medium', 'cs-sample', 'task-old-name', 'task-old-work', ${'a'.repeat(32)}, 'untouched-token-hash', '{}', ${user}, now(), now(), now())`);
      await tdb.db.execute(sql`INSERT INTO platform_infra.jobs (kind, payload, dedup_key) VALUES ('task-runtime.native-execution', ${JSON.stringify({ taskId: task })}::text::jsonb, ${task})`);
      const tab = '00000000-0000-4000-8000-000000000042', terminal = 'pty_old-42', agent = 'agt_old-42', runner = 'old-runner-42';
      const layout = { activeTabId: tab, tabs: [{ id: tab, name: '旧工作区', layout: 'grid', paneOrder: [terminal], ratios: { columns: [1], rows: [1] } }], hiddenTerminalIds: [], view: 'cli', previewAlongside: false, previewRatio: 0.5, selectedTerminalId: terminal, maximizedTerminalId: null, preferredCompute: 'retired-shell' };
      await tdb.db.execute(sql`INSERT INTO dev_session.workspace_layouts (task_id,user_id,revision,layout) VALUES (${task},${user},1,${JSON.stringify(layout)}::text::jsonb)`);
      const item = { agentId: agent, terminalId: terminal, runnerId: runner, eventId: 'old-event-hash', request: { resolvedByEventId: 'old-resolved-hash' } };
      const projection = { state: { agentId: agent, terminalId: terminal, runnerId: runner, pending: [{ eventId: 'old-event-hash' }] } };
      await tdb.db.execute(sql`INSERT INTO dev_session.native_activity_items (task_id,seq,event_id,agent_id,kind,item) VALUES (${task},1,'old-event-hash',${agent},'request',${JSON.stringify(item)}::text::jsonb)`);
      await tdb.db.execute(sql`INSERT INTO dev_session.native_activity_states (task_id,agent_id,projection) VALUES (${task},${agent},${JSON.stringify(projection)}::text::jsonb)`);
      await tdb.db.execute(sql`INSERT INTO data.task_bindings (id,task_id,service_id,project_id,mode,state,requested_by,ttl_minutes,created_at,updated_at) VALUES ('dbnd_original-suffix',${task},${service},${project},'diagnostic-readonly','requested',${user},30,now(),now())`);
      const cluster = { resources: [{ purpose: 'development-cli', profile: 'retired-cluster-cli' }, { purpose: 'development-workspace', profile: 'coding-medium' }], facts: {} };
      await tdb.db.execute(sql`INSERT INTO cluster_management.snapshots (id,created_at,body) VALUES ('snapshot-old',now(),${JSON.stringify(cluster)}::text::jsonb)`);
      const applied = await runMigrations(tdb.db, migrations);
      const [binding] = await tdb.db.execute(sql`SELECT id,legacy_resource_id FROM data.task_bindings`) as unknown as { id: string; legacy_resource_id: string }[];
      expect(binding!.legacy_resource_id).toBe('dbnd_original-suffix');
      expect(ResourceIdSchema.safeParse(binding!.id).success).toBe(true);
      const [snapshotRow] = await tdb.db.execute(sql`SELECT body,legacy_body FROM cluster_management.snapshots`) as unknown as { body: typeof cluster; legacy_body: unknown }[];
      expect(snapshotRow!.legacy_body).toEqual(cluster);
      expect(snapshotRow!.body.resources.every((resource) => ResourceIdSchema.safeParse(resource.profile).success)).toBe(true);
      expect(snapshotRow!.body.resources[0]!.profile).not.toBe(snapshotRow!.body.resources[1]!.profile);
      expect([...(await tdb.db.execute(sql`SELECT count(*)::int AS n FROM agent_runtime.retired_profile_identities WHERE name = 'retired-cluster-cli'`))]).toEqual([{ n: 1 }]);
      expect(applied.length).toBeGreaterThan(20);
      const [row] = await tdb.db.execute(sql`SELECT id, project_id, service_id, created_by, profile, pod_name, pvc_name, runner_token_hash FROM task_runtime.environments`) as unknown as Record<string, string>[];
      for (const key of ['id', 'project_id', 'service_id', 'created_by', 'profile']) expect(ResourceIdSchema.safeParse(row![key]).success).toBe(true);
      expect(new Set([row!.id, row!.project_id, row!.service_id, row!.created_by]).size).toBe(4);
      expect(row).toMatchObject({ pod_name: 'task-old-name', pvc_name: 'task-old-work', runner_token_hash: 'untouched-token-hash' });
      const [snapshot] = await tdb.db.execute(sql`SELECT legacy_manifest, manifest, identity_provenance FROM release.releases`) as unknown as { legacy_manifest: unknown; manifest: { spec: { service: { servicePlanId: string }; env: { configDefinitionId: string }[]; tasks: { agentProfiles: { id: string; compute: unknown }[] } } }; identity_provenance: { originalHash: string; normalizedHash: string } }[];
      expect(snapshot!.legacy_manifest).toEqual(manifest);
      expect(ResourceIdSchema.safeParse(snapshot!.manifest.spec.service.servicePlanId).success).toBe(true);
      expect(ResourceIdSchema.safeParse(snapshot!.manifest.spec.env[0]!.configDefinitionId).success).toBe(true);
      expect(snapshot!.manifest.spec.tasks.agentProfiles[0]!.compute).toEqual({ kind: 'default' });
      expect(snapshot!.identity_provenance.originalHash).not.toBe(snapshot!.identity_provenance.normalizedHash);
      expect([...(await tdb.db.execute(sql`SELECT payload->>'taskId' AS task, dedup_key FROM platform_infra.jobs`))]).toEqual([{ task: row!.id, dedup_key: row!.id }]);
      const [workspace] = await tdb.db.execute(sql`SELECT layout, legacy_layout FROM dev_session.workspace_layouts`) as unknown as { layout: unknown; legacy_layout: unknown }[];
      const upgraded = WorkspaceLayoutSchema.parse(workspace!.layout);
      expect(workspace!.legacy_layout).toEqual(layout);
      expect(upgraded.selectedTerminalId).toBe(upgraded.tabs[0]!.paneOrder[0]!);
      expect(upgraded.activeTabId).toBe(upgraded.tabs[0]!.id);
      expect(upgraded.maximizedTerminalId).toBeNull();
      const [activity] = await tdb.db.execute(sql`SELECT event_id,item,legacy_item FROM dev_session.native_activity_items`) as unknown as { event_id: string; item: typeof item; legacy_item: unknown }[];
      expect(activity!.legacy_item).toEqual(item);
      for (const value of [activity!.event_id, activity!.item.agentId, activity!.item.runnerId, activity!.item.request.resolvedByEventId]) expect(ResourceIdSchema.safeParse(value).success).toBe(true);
      expect(activity!.item.eventId).toBe(activity!.event_id);
      expect(activity!.item.terminalId).toBe(upgraded.selectedTerminalId!);
      expect((await tdb.db.execute(sql`SELECT projection->'state'->'pending'->0->>'eventId' AS id FROM dev_session.native_activity_states`))[0]).toEqual({ id: activity!.event_id });
      expect(await runMigrations(tdb.db, migrations)).toEqual([]);
    } finally { await tdb.drop(); }
  }, 60_000);
});
