import { useState } from 'react';
import type { ProjectResourceNode } from '@crewstation/contracts';
import { useT } from '../../../shared/lib/useT';
import { Button } from '../../../shared/ui/Button';
import { Badge } from '../../../shared/ui/Badge';
import { DataTable } from '../../../shared/ui/DataTable';
import { metricLimit, metricLabel, matches, actionLabel } from '../model/workspace';
import styles from './ResourceCenter.module.css';

export function ResourceList({ nodes, onSelect, permissions = false, readOnly = false }: { nodes: ProjectResourceNode[]; onSelect: (id: string) => void; permissions?: boolean; readOnly?: boolean }) {
  const [limit, setLimit] = useState(50), [q, setQuery] = useState(''), [access, setAccess] = useState(''), t = useT();
  const visible = permissions ? nodes.filter((node) => matches(node, { q, access })) : nodes;
  return <>{permissions ? <div className={styles.toolbar}><div className={styles.controls}><input type="search" aria-label={t('resourceCenter.searchPermissions')} placeholder={t('resourceCenter.searchPermissions')} value={q} onChange={(event) => { setQuery(event.target.value); setLimit(50); }} /><select aria-label={t('resourceCenter.filterPermissions')} value={access} onChange={(event) => { setAccess(event.target.value); setLimit(50); }}><option value="">{t('resourceCenter.allAccess')}</option>{['owned', 'requestable', 'pending', 'unavailable'].map((value) => <option key={value} value={value}>{t(`resourceCenter.access.${value}`)}</option>)}</select></div><small className={styles.muted}>{t('resourceCenter.permissionsCount', { visible: visible.length, total: nodes.length })}</small></div> : null}<DataTable columns={['resource', permissions ? 'permissions' : 'access', 'quota', 'source', 'state', 'actions'].map((v) => t(`resourceCenter.${v}`))}>
    {visible.slice(0, limit).map((node) => <tr key={node.id}><td><strong>{node.name}</strong><small className={styles.block}>{node.description || node.resourceType}</small></td><td><Badge tone={node.access === 'pending' ? 'warning' : node.access === 'requestable' ? 'info' : 'neutral'}>{t(`resourceCenter.access.${node.access}`)}</Badge>{node.pendingRequestIds.length > 0 && node.access !== 'pending' ? <small className={styles.block}>{t('resourceCenter.pending')} · {node.pendingRequestIds.length}</small> : null}{permissions ? <small className={styles.block}>{!readOnly && node.actions.some((a) => a.enabled) ? node.actions.filter((a) => a.enabled).map((a) => actionLabel(a, t)).join(' · ') : t('resourceCenter.viewOnly')}</small> : null}</td><td>{node.metrics.length ? node.metrics.slice(0, 2).map((m) => <small className={styles.block} key={`${m.scopeId}:${m.key}`}>{metricLabel(m, t)} · {metricLimit(m, t)}</small>) : '—'}</td><td>{t(`resourceCenter.source.${node.source}`)}<small className={styles.block}>{t(`resourceCenter.environment.${node.environment}`)}</small></td><td><Badge tone={node.stale ? 'warning' : /failed/.test(node.state) ? 'danger' : 'neutral'}>{node.stale ? t('resourceCenter.stale') : node.stateText}</Badge></td><td><Button size="small" onClick={() => onSelect(node.id)}>{t('resourceCenter.details')}</Button></td></tr>)}
  </DataTable>{!visible.length ? <p className={styles.empty}>{t('resourceCenter.empty')}</p> : null}{visible.length > limit ? <Button onClick={() => setLimit(limit + 50)}>{t('resourceCenter.more')} · {limit} / {visible.length}</Button> : null}</>;
}
