import type { ClusterCapacity, ClusterDemand, ClusterMetric, ClusterNode, ClusterUsage, ClusterUsageSummary } from '@crewstation/contracts';
import { clusterFixture } from './clusterManagementFixture';

export function clusterMetricsFixture() {
  const base = clusterFixture(), fallback = globalThis.fetch, at = new Date().toISOString(), nodeId = '01a0c000-0000-7000-8000-000000000001';
  const demand: ClusterDemand = { requests: { cpu: '0.25', memory: '134217728', 'example.com/gpu': '1' }, limits: { cpu: '2', memory: '1073741824' }, missingRequests: { cpu: 1 }, unboundedLimits: { memory: 1 }, errors: [] };
  const metric = (value: string, unit: ClusterMetric['unit'] = 'bytes'): ClusterMetric => ({ value, unit, state: 'fresh', observedAt: at, source: 'kubelet-summary' });
  const metrics = { cpu: metric('1.25', 'cores'), memory: metric('536870912'), fsUsed: metric('2147483648'), fsCapacity: metric('10737418240'), fsAvailable: metric('8589934592'), networkRx: metric('1024', 'bytes/s'), networkTx: metric('2048', 'bytes/s'), ephemeralStorage: metric('4096') };
  const coverage = { cpu: { expected: 2, observed: 1, fresh: 1, missing: 1, complete: false, errors: ['node-b: 403'] } };
  const summary: ClusterUsageSummary = { pods: 1, pvcs: 1, demand, pendingDemand: demand, storageRequested: '1073741824', storageCapacity: '1073741824', metrics: { ...metrics, volumeUsed: metric('2147483648') }, coverage };
  const capacity: ClusterCapacity = { observationId: 'observation-a', inventorySnapshotId: base.summary.snapshotId, observedAt: at, scope: 'cluster', state: 'fresh', errors: ['node-b: 403'], nodes: 2, readyNodes: 1, schedulableNodes: 1, podCount: 5, pendingPods: 1, capacity: { cpu: '10', memory: '17179869184', 'example.com/gpu': '2' }, allocatable: { cpu: '9', memory: '16106127360', 'example.com/gpu': '2' }, demand, pendingDemand: demand, metrics, coverage, managed: summary, system: summary, projects: { [base.projectId]: summary } };
  const node: ClusterNode = { resourceId: nodeId, uid: 'node-uid', name: 'worker-node-a', roles: ['control-plane'], version: 'v1.36.1', ready: true, unschedulable: true, conditions: [{ type: 'DiskPressure', status: 'False', reason: 'Sufficient space' }], capacity: capacity.capacity, allocatable: capacity.allocatable, demand, podCount: 4, metrics: { ...metrics, fsInodes: metric('100', 'count'), fsInodesUsed: metric('2', 'count'), imageFsUsed: metric('1024'), containerFsUsed: metric('1024') }, interfaces: { eth0: metrics }, devices: { '/dev/vda': { diskRead: metric('100', 'bytes/s'), diskWrite: metric('200', 'bytes/s'), diskReadOps: metric('2', 'ops/s'), diskWriteOps: metric('4', 'ops/s') } }, managedPodIds: [base.row.resourceId], errors: [] };
  const pod: ClusterUsage = { resourceId: base.row.resourceId, uid: base.row.uid, kind: 'Pod', namespace: base.row.namespace, name: base.row.name, scope: 'project', projectId: base.projectId, node: node.name, phase: 'Running', demand, metrics, qos: 'Burstable', hostNetwork: true, podRequests: { cpu: '2' }, containers: ['application', 'init', 'sidecar', 'ephemeral'].map((type, i): ClusterUsage['containers'][number] => ({ name: ['main', 'init', 'sidecar', 'debug'][i]!, type: type as ClusterUsage['containers'][number]['type'], image: 'worker:v1', state: i === 1 ? 'terminated' : 'running', startedAt: at, requests: i === 3 ? {} : { cpu: '250m', memory: '128Mi' }, limits: i === 3 ? {} : { cpu: '1' }, metrics: i === 1 ? { cpu: { state: 'unavailable', unit: 'cores', source: 'kubelet-summary', reason: 'Container is not running' } } : metrics })) };
  const pvc: ClusterUsage = { resourceId: '01a0c000-0000-7000-8000-000000000002', uid: 'pvc-uid', kind: 'PersistentVolumeClaim', namespace: base.row.namespace, name: 'workspace-volume', scope: 'project', projectId: base.projectId, phase: 'Bound', node: node.name, demand, metrics: { volumeUsed: metric('2147483648') }, containers: [], storage: { requested: '1073741824', capacity: '1073741824', storageClass: 'standard', accessModes: ['ReadWriteOnce'], volumeMode: 'Filesystem', mounts: [{ resourceId: base.row.resourceId, name: base.row.name, node: node.name }], hardQuota: false, volumeName: 'pv-work', source: 'local-path-probe' } };
  const podRow = { ...base.row, kind: 'Pod', view: 'pods' as const, node: node.name, containers: pod.containers.map((c) => ({ ...c, init: c.type === 'init' || c.type === 'sidecar', ready: true, restarts: 0, ports: [] })) };
  const pvcRow = { ...base.row, ...pvc, view: 'storage' as const, containers: [], ownership: base.row.ownership };
  const calls: URL[] = []; let historyError = false, stale = false;
  globalThis.fetch = (async (raw, init) => {
    const url = new URL(String(raw), 'http://localhost'); calls.push(url);
    if (url.pathname.endsWith('/capacity')) return Response.json(capacity);
    if (url.pathname.endsWith('/nodes')) return Response.json({ observationId: 'observation-a', observedAt: at, items: [node], total: 1 });
    if (url.pathname.endsWith('/usage')) return Response.json({ observationId: 'observation-a', inventorySnapshotId: base.summary.snapshotId, observedAt: at, items: [pod, { ...pvc, metrics: stale ? { volumeUsed: { ...pvc.metrics.volumeUsed!, state: 'stale', reason: 'Probe unavailable' } } : pvc.metrics }], summary });
    if (url.pathname.endsWith('/history/resources')) return Response.json({ total: 1, items: [{ resourceId: pvc.resourceId, uid: 'old-pvc-uid', kind: 'PersistentVolumeClaim', name: 'old-volume', namespace: pvc.namespace, scope: 'project', projectId: base.projectId, firstSeen: at, lastSeen: at, deleted: true, versions: [] }] });
    if (url.pathname.endsWith('/history')) {
      const points = Array.from({ length: 4 }, (_, i) => ({ at: new Date(Date.parse(at) - (3 - i) * 15000).toISOString(), average: i === 1 ? null : 1, peak: i === 1 ? null : 2, complete: i !== 1, coverage: i === 1 ? 0 : 1 }));
      return Response.json({ requestedFrom: url.searchParams.get('from'), requestedTo: url.searchParams.get('to'), availableFrom: at, stepSeconds: 15, source: 'prometheus', state: historyError ? 'error' : 'fresh', ...(historyError ? { reason: 'History storage HTTP 503' } : {}), series: (url.searchParams.get('metrics') ?? 'cpu').split(',').map((metric) => ({ metric, unit: metric.startsWith('cpu') ? 'cores' : 'bytes', points })) });
    }
    if (url.pathname.endsWith('/resources') && url.searchParams.get('view') === 'storage') return Response.json({ snapshotId: base.summary.snapshotId, complete: true, items: [pvcRow, { ...base.row, kind: 'ConfigMap', resourceId: 'config-id', uid: 'config-uid', name: 'configuration', view: 'storage' }], total: 2 });
    if (url.pathname.endsWith('/resources') && url.searchParams.get('view') === 'pods') return Response.json({ snapshotId: base.summary.snapshotId, complete: true, items: [podRow], total: 1 });
    if (url.pathname.endsWith(`/resources/${base.row.resourceId}`)) return Response.json({ resource: podRow, related: [], complete: true, sources: [] });
    if (url.pathname.endsWith(`/resources/${pvc.resourceId}`)) return Response.json({ resource: pvcRow, related: [], complete: true, sources: [] });
    return fallback(raw, init);
  }) as typeof fetch;
  return { ...base, capacity, node, pod, pvc, calls, historyFailure: () => { historyError = true; }, staleStorage: () => { stale = true; } };
}
