import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import { eq } from 'drizzle-orm';
import { jsonHash, newResourceId } from '@crewstation/kernel';
import type { BusinessOperationDto, BusinessSubtaskV3Dto } from '@crewstation/contracts';
import { createTestDatabase, testDatabaseAvailable, type TestDatabase } from '@crewstation/testkit';
import { businessTaskMigrations } from '../wiring';
import { taskRecoveryFixture } from './taskRecoveryFixture';
import { recoveryAudit, recoveryRequests } from '../adapters/persistence/recovery/tables';
import { executionTaskStates, executionLifecycles } from '../adapters/persistence/execution/lifecycleTables';
import { executionLogs } from '../adapters/persistence/execution/projectionTables';
import { executionSubtasks } from '../adapters/persistence/execution/subtaskTables';

const available = await testDatabaseAvailable();
describe.skipIf(!available)('RFC029 恢复请求与实际操作原子关联', () => {
  let tdb: TestDatabase;
  beforeAll(async () => { tdb = await createTestDatabase([businessTaskMigrations]); });
  afterAll(async () => { await tdb?.drop(); });
  const paused = async () => {
    const f = await taskRecoveryFixture(tdb.db); f.env.state = 'paused'; f.env.connected = false;
    let starts = 0;
    f.environmentPort.resumeEnvironment = async () => { starts++; f.env.state = 'creating'; return f.env; };
    const saved = await f.repository.request(f.admission), claim = (await f.repository.claim(f.serviceId, f.authorization))!;
    const body = { requestKey: `recovery:${saved.id}`, expectedGeneration: 2, fence: f.fence, recovery: { recoveryRequestId: saved.id, claimId: claim.claimId } };
    return { ...f, saved, claim, body, starts: () => starts, path: `/v3/business-tasks/${f.task.id}/resume` };
  };
  test('真实 resume 操作受理与关联同事务；刷新、实例重启和认领更替不重复恢复', async () => {
    const f = await paused();
    const responses = await Promise.all(Array.from({ length: 4 }, () => f.request(f.path, f.body)));
    expect(responses.map((r) => r.status)).toEqual([202, 202, 202, 202]);
    const operations = await Promise.all(responses.map((r) => r.json() as Promise<BusinessOperationDto>));
    expect(new Set(operations.map((r) => r.operationId)).size).toBe(1); expect(f.starts()).toBe(1);
    expect(await f.repository.get(f.serviceId, f.saved.id)).toMatchObject({ state: 'running', operationId: operations[0]!.operationId });
    expect(await f.repository.reconcile()).toBe(0);
    expect((await f.make().request(f.path, f.body)).status).toBe(202); expect(f.starts()).toBe(1);
    await tdb.db.update(recoveryRequests).set({ leaseUntil: new Date(0) }).where(eq(recoveryRequests.id, f.saved.id));
    const second = (await f.repository.claim(f.serviceId, f.authorization, f.saved.id))!;
    expect(second.request.state).toBe('running');
    const resumedBody = { ...f.body, recovery: { ...f.body.recovery, claimId: second.claimId } };
    expect((await f.request(f.path, resumedBody)).status).toBe(202); expect(f.starts()).toBe(1);
    await expect(f.repository.reject(f.serviceId, f.saved.id, { authorization: f.authorization, claimId: second.claimId }, 'fake failure')).rejects.toMatchObject({ kind: 'conflict' });
    f.env.state = 'running'; f.env.connected = true;
    for (let i = 0; i < 4; i++) await f.make().module.api.v3.runOnce();
    expect(await f.repository.get(f.serviceId, f.saved.id)).toMatchObject({ state: 'succeeded', operationId: operations[0]!.operationId });
    expect((await f.request(f.path, resumedBody)).status).toBe(202); expect(f.starts()).toBe(1);
    expect(await f.repository.get(f.serviceId, f.saved.id)).toMatchObject({ state: 'succeeded' });
    expect((await tdb.db.select().from(recoveryAudit).where(eq(recoveryAudit.requestId, f.saved.id))).map((r) => r.event)).toEqual(['requested', 'claimed', 'running', 'claimed', 'succeeded']);
  });
  test('伪造 key／claim／generation 与把恢复用于 close 均无副作用；实际失败才能置失败', async () => {
    const f = await paused();
    for (const delta of [{ requestKey: 'unrelated' }, { expectedGeneration: 1 }, { recovery: { ...f.body.recovery, claimId: newResourceId() } }, { fence: { ...f.fence, epoch: f.fence.epoch + 1 } }]) expect((await f.request(f.path, { ...f.body, ...delta })).status).toBe(409);
    expect((await f.request(f.path.replace('/resume', '/close'), f.body)).status).toBe(412); expect(f.starts()).toBe(0);
    expect(await f.repository.get(f.serviceId, f.saved.id)).toMatchObject({ state: 'claimed' });
    const operation = await (await f.request(f.path, f.body)).json() as BusinessOperationDto;
    await tdb.db.update(executionLifecycles).set({ state: 'failed', errorCode: 'resume_failed' }).where(eq(executionLifecycles.id, operation.operationId));
    expect(await f.repository.reconcile()).toBe(1); expect(await f.repository.get(f.serviceId, f.saved.id)).toMatchObject({ state: 'failed', reason: 'resume_failed' });
  });
  test('子任务恢复通过原 retry 路由只创建一个 attempt，认领标识更替不改变幂等摘要', async () => {
    const f = await taskRecoveryFixture(tdb.db);
    await tdb.db.update(executionTaskStates).set({ state: 'running' }).where(eq(executionTaskStates.taskId, f.task.id));
    await tdb.db.update(executionLogs).set({ taskState: 'running' }).where(eq(executionLogs.taskId, f.task.id));
    f.behavior.disconnectAfterInfo = true;
    const original = await (await f.request(f.path, f.input)).json() as BusinessSubtaskV3Dto;
    expect((await f.request(`${f.path}/${original.id}/cancel`, { requestKey: 'cancel-before-start', expectedAttempt: 1, fence: f.fence })).status).toBe(202);
    f.behavior.disconnectAfterInfo = false; f.env.connected = true;
    const row = (await tdb.db.select().from(executionSubtasks).where(eq(executionSubtasks.id, original.id)))[0]!;
    const target = { taskId: f.task.id, action: 'retry-subtask' as const, expectedGeneration: 2, subtaskId: original.id, expectedAttempt: 1, materialDigest: jsonHash({ parent: f.admission.request.target.materialDigest, child: row.payloadDigest }) };
    const saved = await f.repository.request({ ...f.admission, request: { ...f.admission.request, target } }), claim = (await f.repository.claim(f.serviceId, f.authorization))!;
    const input = { requestKey: `recovery:${saved.id}`, expectedAttempt: 1, resumePolicy: 'fresh', fence: f.fence, recovery: { recoveryRequestId: saved.id, claimId: claim.claimId } };
    const path = `${f.path}/${original.id}/retry`;
    expect((await f.request(path, { ...input, requestKey: 'wrong-key' })).status).toBe(409);
    expect((await f.request(path, { ...input, resumePolicy: 'resume', resumeSessionId: 'fabricated' })).status).toBe(409);
    const responses = await Promise.all(Array.from({ length: 4 }, () => f.request(path, input)));
    expect(responses.every((r) => [200, 201].includes(r.status))).toBe(true);
    const next = await Promise.all(responses.map((r) => r.json() as Promise<BusinessSubtaskV3Dto>));
    expect(new Set(next.map((r) => r.id)).size).toBe(1); expect(next[0]).toMatchObject({ attempt: 2, previousId: original.id }); expect(f.behavior.starts).toBe(1);
    expect(await f.repository.get(f.serviceId, saved.id)).toMatchObject({ state: 'running', resultSubtaskId: next[0]!.id });
    await tdb.db.update(recoveryRequests).set({ leaseUntil: new Date(0) }).where(eq(recoveryRequests.id, saved.id));
    const second = (await f.repository.claim(f.serviceId, f.authorization, saved.id))!;
    expect((await f.make().request(path, { ...input, recovery: { ...input.recovery, claimId: second.claimId } })).status).toBe(200); expect(f.behavior.starts).toBe(1);
    await tdb.db.update(executionSubtasks).set({ view: { ...next[0]!, state: 'succeeded', process: 'exited' } }).where(eq(executionSubtasks.id, next[0]!.id));
    expect(await f.repository.reconcile()).toBe(1);
    expect(await f.repository.get(f.serviceId, saved.id)).toMatchObject({ state: 'succeeded', resultSubtaskId: next[0]!.id });
    expect((await f.request(path, { ...input, recovery: { ...input.recovery, claimId: second.claimId } })).status).toBe(200); expect(f.behavior.starts).toBe(1);
    expect((await f.request(`${f.path}/${original.id}`)).status).toBe(200);
  });
});
