import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import { eq, sql } from 'drizzle-orm';
import type { BusinessRecoveryAssessment, RequestBusinessRecovery } from '@crewstation/contracts';
import { createApp } from '@crewstation/http';
import { newResourceId } from '@crewstation/kernel';
import { createTestDatabase, testDatabaseAvailable, type TestDatabase } from '@crewstation/testkit';
import { businessTaskMigrations } from '../wiring';
import { userRoutes } from '../http/userRoutes';
import { taskRecoveryFixture } from './taskRecoveryFixture';
import { executionControls } from '../adapters/persistence/executionTables';
import { recoveryAudit, recoveryRequests } from '../adapters/persistence/recovery/tables';
import { contracts } from '../adapters/persistence/tables';
import { executionSubtasks } from '../adapters/persistence/execution/subtaskTables';
import { BusinessRecoveryTaskDetailSchema, BusinessSubtaskV3DtoSchema } from '@crewstation/contracts';

const available = await testDatabaseAvailable();
describe.skipIf(!available)('RFC029 管理员恢复评估与请求 HTTP', () => {
  let tdb: TestDatabase;
  beforeAll(async () => { tdb = await createTestDatabase([businessTaskMigrations]); });
  afterAll(async () => { await tdb?.drop(); });
  const fixture = async () => {
    const f = await taskRecoveryFixture(tdb.db), admin = newResourceId(), access = { allowed: true };
    f.env.state = 'paused'; f.env.connected = false; f.env.image = 'original:task';
    const proof = { state: 'paused', persistent: true, stopped: true, activeChildren: false, volumeUid: 'original-pvc', volumeVerified: true, image: 'original:task' };
    f.environmentPort.inspectBusinessRecovery = async () => ({ ...proof });
    const app = createApp({ name: 'recovery-admin' }); app.route('/', userRoutes(f.module.api, async (id) => access.allowed && id === admin));
    const path = `/v1/admin/business-execution/tasks/${f.task.id}/recovery`;
    const request = (url = path, body?: unknown, user = admin) => app.request(url, { method: body === undefined ? 'GET' : 'POST', headers: { ...(user ? { 'x-cs-user-id': user } : {}), 'content-type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    return { ...f, path, request, proof, access, admin };
  };
  test('只读评估不认领；重复点击、响应丢失和应用离线后仍返回同一持久请求', async () => {
    const f = await fixture(), before = await tdb.db.select().from(executionControls).where(eq(executionControls.serviceId, f.serviceId));
    const response = await f.request(); expect(response.status).toBe(200);
    const assessment = await response.json() as BusinessRecoveryAssessment;
    expect(assessment.actions).toHaveLength(1); expect(assessment.actions[0]?.target).toEqual(f.admission.request.target);
    expect(await tdb.db.select().from(executionControls).where(eq(executionControls.serviceId, f.serviceId))).toEqual(before);
    expect(await f.repository.list(f.serviceId, f.task.id, 10)).toEqual([]);
    const input: RequestBusinessRecovery = { ...assessment.actions[0]!, requestKey: 'admin-click' };
    const responses = await Promise.all([f.request(f.path, input), f.request(f.path, input)]);
    expect(responses.map((r) => r.status)).toEqual([202, 202]);
    const one = await responses[0]!.json(), two = await responses[1]!.json(); expect(two).toEqual(one);
    expect(one).toMatchObject({ requestedBy: f.admin, state: 'pending' });
    expect(await (await f.request(f.path + '/requests')).json()).toEqual({ items: [one] });
    expect((await tdb.db.select().from(recoveryAudit).where(eq(recoveryAudit.requestId, one.id))).map((r) => r.event)).toEqual(['requested']);
    await tdb.db.delete(executionControls).where(eq(executionControls.serviceId, f.serviceId));
    expect(await (await f.request(f.path, input)).json()).toEqual(one);
    expect((await f.request(f.path, { ...input, target: { ...input.target, expectedGeneration: 99 } })).status).toBe(409);
    expect(JSON.stringify(one)).not.toContain('leaseId'); expect(JSON.stringify(one)).not.toContain('sealedPayload');
    f.access.allowed = false;
    expect((await f.request(f.path + '/requests')).status).toBe(403);
    expect((await f.request(f.path, input)).status).toBe(403);
  });
  test('受理重新核实卷、旧进程和控制权，不信任浏览器旧评估或目标', async () => {
    const f = await fixture(), response = await f.request(); expect(response.status).toBe(200);
    const assessment = await response.json() as BusinessRecoveryAssessment;
    const input: RequestBusinessRecovery = { ...assessment.actions[0]!, requestKey: 'stale-click' };
    f.proof.volumeVerified = false;
    expect((await f.request(f.path, input)).status).toBe(412);
    expect(await (await f.request()).json()).toMatchObject({ actions: [], reasons: ['original_workspace_unavailable'] });
    f.proof.volumeVerified = true; f.proof.stopped = false;
    expect(await (await f.request()).json()).toMatchObject({ actions: [], reasons: ['original_execution_not_stopped'] });
    expect((await f.request(f.path, input)).status).toBe(412);
    f.proof.stopped = true;
    await tdb.db.update(executionControls).set({ body: sql`body || '{"epoch":99}'::jsonb` }).where(eq(executionControls.serviceId, f.serviceId));
    expect((await f.request(f.path, input)).status).toBe(412);
    expect((await f.request(f.path, { ...input, target: { ...input.target, taskId: newResourceId() } })).status).toBe(400);
    expect(await f.repository.list(f.serviceId, f.task.id, 10)).toEqual([]);
  });
  test('第二次点击评估期间首次请求已提交，仍返回相同回执而非虚报评估过期', async () => {
    const f = await fixture(), assessment = await (await f.request()).json() as BusinessRecoveryAssessment;
    const input = { ...assessment.actions[0]!, requestKey: 'overlapping-click' };
    let release!: () => void, observations = 0;
    const gate = new Promise<void>((resolve) => { release = resolve; });
    f.environmentPort.inspectBusinessRecovery = async () => { if (++observations === 2) await gate; return f.proof; };
    const one = f.request(f.path, input), two = f.request(f.path, input);
    await Promise.race([one, two]).finally(release);
    const responses = await Promise.all([one, two]);
    expect(responses.map((r) => r.status)).toEqual([202, 202]);
    expect(await responses[0]!.json()).toEqual(await responses[1]!.json());
    expect(await f.repository.list(f.serviceId, f.task.id, 100)).toHaveLength(1);
  });
  test('长历史仍保留未完成请求，刷新后不会遗漏正在恢复的任务', async () => {
    const f = await fixture(), assessment = await (await f.request()).json() as BusinessRecoveryAssessment;
    const input = { ...assessment.actions[0]!, requestKey: 'long-running' };
    const saved = await (await f.request(f.path, input)).json();
    const row = (await tdb.db.select().from(recoveryRequests).where(eq(recoveryRequests.id, saved.id)))[0]!;
    await tdb.db.update(recoveryRequests).set({ createdAt: new Date('2020-01-01') }).where(eq(recoveryRequests.id, saved.id));
    await tdb.db.insert(recoveryRequests).values(Array.from({ length: 105 }, (_, i) => ({ ...row, id: newResourceId(), requestKey: `history-${i}`, state: 'succeeded' as const })));
    const page = await (await f.request(f.path + '/requests')).json();
    expect(page.items).toHaveLength(100); expect(page.items[0].id).toBe(saved.id);
    expect(await (await f.request()).json()).toMatchObject({ actions: [], reasons: ['task_operation_pending'] });
  });
  test('权限与参数严格校验；无资源证据、离线或未声明能力显示真实原因', async () => {
    const f = await fixture();
    expect((await f.request(f.path, undefined, '')).status).toBe(401);
    expect((await f.request(f.path, undefined, newResourceId())).status).toBe(403);
    expect((await f.request(f.path + '?extra=1')).status).toBe(400);
    expect((await f.request(f.path + '?subtaskId=bad')).status).toBe(400);
    expect((await f.request(f.path.replace(f.task.id, newResourceId()))).status).toBe(404);
    expect((await f.request(f.path + '?subtaskId=' + newResourceId())).status).toBe(404);
    f.environmentPort.inspectBusinessRecovery = async () => { throw new Error('cluster offline'); };
    expect(await (await f.request()).json()).toMatchObject({ actions: [], reasons: ['resource_observation_unavailable'] });
    await tdb.db.update(contracts).set({ tasksSpec: sql`tasks_spec - 'recovery'` }).where(eq(contracts.releaseId, f.releaseId));
    expect(await (await f.request()).json()).toMatchObject({ actions: [], reasons: ['application_recovery_unsupported'] });
    await tdb.db.delete(executionControls).where(eq(executionControls.serviceId, f.serviceId));
    expect((await (await f.request()).json()).reasons).toContain('application_controller_offline');
  });
  test('任务详情读取原任务和全部执行尝试，不泄露加密材料或触发恢复；撤权后不可读取', async () => {
    const f = await fixture(), id = newResourceId();
    f.env.message = '原容器启动失败';
    const view = BusinessSubtaskV3DtoSchema.parse({ id, taskId: f.task.id, name: '失败步骤', kind: 'command', state: 'failed', process: 'exited', attempt: 1, executionId: newResourceId(), createdAt: new Date().toISOString(), error: { code: 'command_failed', message: 'exit 1' } });
    await tdb.db.insert(executionSubtasks).values({ id, serviceId: f.serviceId, taskId: f.task.id, requestKey: 'detail-child', requestDigest: 'a', payloadDigest: 'b', sealedPayload: 'must-not-be-returned', fenced: true, view, dispatch: 'accepted', updatedAt: new Date() });
    const path = f.path.replace('/recovery', ''), response = await f.request(path);
    expect(response.status).toBe(200);
    const detail = BusinessRecoveryTaskDetailSchema.parse(await response.json());
    expect(detail.task).toMatchObject({ id: f.task.id, state: 'paused', generation: 2, message: '原容器启动失败' }); expect(detail.subtasks).toEqual([view]);
    expect(JSON.stringify(detail)).not.toContain('must-not-be-returned');
    expect(await f.repository.list(f.serviceId, f.task.id, 100)).toHaveLength(0);
    expect((await f.request(path.replace(f.task.id, newResourceId()))).status).toBe(404);
    f.access.allowed = false; expect((await f.request(path)).status).toBe(403);
  });
});
